### ISSUE TITLE
Arrow never despawn

### ISSUE THREAD

**Issue by OoyanwoO** [Truly-Modular/Archery#6]
Once TM arrow is shot, it will never disappear. Maybe add a feature to cap the arrow count in world or let it disappear after certain amount of time? This might cause some performance issue for a long term save file.

![2024-07-26_11 27 512](https://github.com/user-attachments/assets/d3de1907-c475-442c-ab5e-8915b7ee11ff)

**Comment by Smartin-b** [comment]
the arrows should have a lifetime of 1200 seconds (20 minutes)
Are you sure they dont despawn after 20 minutes?

**Comment by Smartin-b** [comment]
nvmd, looking at the code there was a bug preventing this from working. will be fixed in the next update
